version: '3'

services:

  client:
    build:
      context: app
      dockerfile: ./Dockerfile.dev
    container_name: teamchat-client
    volumes:
      - './app:/app'
    ports:
      - '3000:3000'

  server:
    build:
      context: ./server
      dockerfile: ./Dockerfile.dev
    container_name: teamchat-php
    ports:
      - "8000:8000"
    volumes:
      - "./server:/application"
    environment:
      XDEBUG_CONFIG: "remote_host=host.docker.internal"
      PHP_IDE_CONFIG: "serverName=server"
      LOG_LEVEL: 'debug'
      APP_ENV: 'dev'
      DATABASE_URL: 'postgresql://symfony:testing123@postgres:5432/internal-messaging?serverVersion=13&charset=utf8'
      TEAMCHAT_REDIS_HOST: 'redis'
      TEAMCHAT_REDIS_PORT: '6379'


  ###> doctrine/doctrine-bundle ###
  postgres:
    image: postgres
    container_name: teamchat-db-data
    environment:
      POSTGRES_DB: internal-messaging
      # You should definitely change the password in production
      POSTGRES_PASSWORD: testing123
      POSTGRES_USER: symfony
    ports:
      - "5433:5432"
    volumes:
      - internal-messaging-db-data:/var/lib/postgresql/data:rw

      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

  redis:
    image: "redis"
    container_name: teamchat-redis
    ports:
      - "6379:6379"


volumes:
###> doctrine/doctrine-bundle ###
  internal-messaging-db-data:
###< doctrine/doctrine-bundle ###
