version: '3'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: internal-messaging
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    volumes:
      - "./:/application"
    environment:
      XDEBUG_CONFIG: "remote_host=host.docker.internal"
      LOG_LEVEL: 'debug'
      APP_ENV: 'dev'
      DATABASE_URL: 'postgresql://symfony:testing123@postgres:5432/internal-messaging?serverVersion=13&charset=utf8'
  ###> doctrine/doctrine-bundle ###
  postgres:
    image: postgres
    container_name: internal-messaging-db-data
    environment:
      POSTGRES_DB: internal-messaging
      # You should definitely change the password in production
      POSTGRES_PASSWORD: testing123
      POSTGRES_USER: symfony
    ports:
      - "5433:5432"
    volumes:
      - internal-messaging-db-data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  internal-messaging-db-data:
###< doctrine/doctrine-bundle ###
