version: '3'

networks:
  messaging-network:
    driver: bridge

services:
  nginx:
    build:
      context: ./apps/nginx
      dockerfile: ./Dockerfile.dev
    container_name: nginx
    ports:
      - "4000:80"
      - "9000:443"
    volumes:
      - "./apps/nginx/default.conf:/etc/nginx/conf.d/default.conf"
    depends_on:
      - server
    networks:
      - messaging-network

  server:
    build:
      context: ./apps/server
      dockerfile: ./Dockerfile.dev
    container_name: server-php
    ports:
      - "8000:8000"
    volumes:
      - "./apps/server:/application"
    environment:
      XDEBUG_CONFIG: "remote_host=host.docker.internal"
      LOG_LEVEL: 'debug'
      APP_ENV: 'dev'
      DATABASE_URL: 'postgresql://symfony:testing123@postgres:5432/internal-messaging?serverVersion=13&charset=utf8'
    networks:
      - messaging-network

  ###> doctrine/doctrine-bundle ###
  postgres:
    image: postgres
    container_name: internal-messaging-db-data
    environment:
      POSTGRES_DB: internal-messaging
      # You should definitely change the password in production
      POSTGRES_PASSWORD: testing123
      POSTGRES_USER: symfony
    ports:
      - "5433:5432"
    volumes:
      - internal-messaging-db-data:/var/lib/postgresql/data:rw
    networks:
      - messaging-network
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###
  client:
    build:
      context: ./apps/client
      dockerfile: ./Dockerfile.dev
    volumes:
      - './apps/client:/applications'
    ports:
      - '3000:3000'
    networks:
      - messaging-network

volumes:
###> doctrine/doctrine-bundle ###
  internal-messaging-db-data:
###< doctrine/doctrine-bundle ###
