framework:
    cache:

        #Redis => utilizes the FrameworkBundle to create a Redis Cache Adapter using a default template.
        #  For Redis, the cache pool (service) is created automatically
        app: cache.adapter.redis
        default_redis_provider: "redis://%env(TEAMCHAT_REDIS_HOST)%:%env(TEAMCHAT_REDIS_PORT)%"





#  Customizing the RedisAdapter.  Create a pool and apply the customization through services.
#        pools:
#            cache.my_redis:
#                adapter: cache.adapter.redis
#                provider: app.my_custom_redis_provider
#
#services:
#    app.my_custom_redis_provider:
#        class: \Redis
#        factory: ['Symfony\Component\Cache\Adapter\RedisAdapter', 'createConnection']
#        arguments:
#            - "redis://%env(TEAMCHAT_REDIS_HOST)%:%env(TEAMCHAT_REDIS_PORT)%"
#            - { retry_interval: 2, timeout: 10 }