<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHvJfIDi\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHvJfIDi/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHvJfIDi.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHvJfIDi\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerHvJfIDi\App_KernelDevDebugContainer([
    'container.build_hash' => 'HvJfIDi',
    'container.build_id' => 'd5b1f57b',
    'container.build_time' => 1662070060,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHvJfIDi');
